language: python
python: 
  - "2.7"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# install dependencies
install:
  - pip install -U pip
  - pip install -r dev-requirements.txt
script:
  - pytest
  
# deploy to PyPI when tags pushed
deploy:
  provider: pypi
  user: "jnoortheen"
  password: $PYPI_PASSWORD
  on:
    tags: true
