language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39

# install dependencies
install:
  - pip install tox
script:
  - tox
  
# deploy to PyPI when tags pushed
deploy:
  provider: pypi
  user: "jnoortheen"
  password: $PYPI_PASSWORD
  on:
    tags: true
