language: python
python: 
  - "2.7"
  - "3.6"
install:
  - pip install -U pip
  - pip install -r dev-requirements.txt
script:
  - pytest
deploy:
  provider: pypi
  user: "jnoortheen"
  password: $PYPI_PASSWORD
  on:
    tags: true
